CREATE TABLE Autos(
id SERIAL PRIMARY KEY,
fullNameAuto CHARACTER VARYING(100),
city CHARACTER VARYING(100),
yearOfRelease INTEGER,
mileage CHARACTER VARYING(30),
engine CHARACTER VARYING(50),
bodywork CHARACTER VARYING(50),
transmission CHARACTER VARYING(30),
drive CHARACTER VARYING(10),
condition CHARACTER VARYING(50),
price CHARACTER VARYING(20),
photo CHARACTER VARYING(500),
url CHARACTER VARYING(500)
);